### ISSUE TITLE
Move https://techconfs.it/ to point here

### ISSUE THREAD

**Issue by cortinico** [cortinico/tech-conferences-italy#70]
Currently https://techconfs.it/ fails to resolve. We'll need a CNAME file in this repo and make sure the DNS are set correctly 👍 @danybony

**Comment by danybony** [comment]
I created the CNAME for www.techconf.it (that's the domain I have) and removed it from my repo. Let's see if it the DNS update is ok, otherwise you might need to manually add it in the repo settings/pages (I don't have access for that)

**Comment by cortinico** [comment]
@danybony I've just realized that I've set up deployment via Vercel (so we can get previews of PRs). The DNS should be updated to point there then:

![Screenshot 2023-02-25 at 11 39 16](https://user-images.githubusercontent.com/3001957/221354893-d899c0e3-f599-4906-945e-53ea23da13b2.png)

**Comment by danybony** [comment]
I updated the DNS but now going to http://www.techconf.it/ it shows the following: 
<img width="629" alt="image" src="https://user-images.githubusercontent.com/3942812/221504509-b18d6368-0cc6-4d3f-b0fd-7460b572fd84.png">
I never used vercel, so any idea?

**Comment by cortinico** [comment]
I believe the DNSs are still not set (ot at least I can't find any record for them with `dig` or with online tools: https://mxtoolbox.com/SuperTool.aspx?action=a%3atechconfs.it&run=toolpage) 🤔
